FROM evoapicloud/evolution-api:latest

ENV SERVER_TYPE=http \
    SERVER_PORT=8080 \
    AUTHENTICATION_TYPE=apikey \
    DATABASE_ENABLED=true \
    DATABASE_PROVIDER=postgresql \
    LOG_LEVEL=info \
    LANGUAGE=en
