import type { PropertyListing, WhatsAppSession } from '../lib/broker-types';

export const MOCK_LISTINGS: PropertyListing[] = [
  {
    id: '1',
    title: 'Luxury 3BHK Apartment in DLF Phase 5',
    type: 'SALE',
    propertyType: 'APARTMENT',
    location: 'Horizon Drive, Sector 54',
    city: 'Gurgaon',
    price: '₹4.5 Cr',
    area: '2450 sqft',
    bhk: 3,
    source: 'WHATSAPP',
    sourceName: 'South Delhi & GG Premium Group',
    timestamp: '2024-05-06T10:30:00Z',
    tags: ['Pool View', 'High Floor', 'Immediate'],
    description: 'Ultra luxury apartment with premium finishings. East facing with clear views.',
    status: 'VERIFIED',
  },
  {
    id: '2',
    title: 'Plot for Boutique House',
    type: 'SALE',
    propertyType: 'PLOT',
    location: 'Block C, Sushant Lok 1',
    city: 'Gurgaon',
    price: '₹8.2 Cr',
    area: '500 sq yards',
    source: 'WHATSAPP',
    sourceName: 'Real Estate Leaders Network',
    timestamp: '2024-05-06T09:15:00Z',
    tags: ['Resale', 'Internal Road'],
    description: 'Perfect rectangular plot for self-construction. Gated community with 24/7 security.',
    status: 'PENDING',
  },
  {
    id: '3',
    title: 'Spacious 4BHK Villa in Hiranandani',
    type: 'RENT',
    propertyType: 'VILLA',
    location: 'Powai',
    city: 'Mumbai',
    price: '₹2.8L/month',
    area: '4200 sqft',
    bhk: 4,
    source: 'WHATSAPP',
    sourceName: 'Mumbai Elite Rentals',
    timestamp: '2024-05-06T08:45:00Z',
    tags: ['Fully Furnished', 'Servant Room'],
    description: 'Independent bungalow with private garden and modular kitchen.',
    status: 'VERIFIED',
  },
];

export const MOCK_SESSIONS: WhatsAppSession[] = [
  {
    id: 'sess-1',
    phoneNumber: '+91 98110XXXXX',
    status: 'CONNECTED',
    lastSeen: 'Active now',
    groupsTracked: 42,
  },
];
