export const ROUTE_PATHS = {
  api: {
    auth: '/api/auth',
    whatsapp: '/api/whatsapp',
    channels: '/api/channels',
    broadcast: '/api/broadcast',
    workspace: '/api/workspace',
    ai: '/api/ai',
    agent: '/api/agent',
    admin: '/api/admin',
    voice: '/api/voice',
    settings: '/api/settings',
    files: '/api/files',
    internal: '/api/internal',
    voiceListen: '/api/voice/listen',
    health: '/health',
    propertiesSearch: '/api/properties/search',
    aiPropertySearch: '/api/ai/property-search',
    identity: '/api/identity',
    brokerContacts: '/api/broker-contacts',
    stream: '/api/stream-items',
    ingest: '/api/listings/ingest',
    intelligence: '/api/intelligence',
    examplePrompts: '/api/example-prompts',
    notifications: '/api/notifications',
    syndication: '/api/syndication',
    whatsappCloud: '/api/whatsapp/cloud',
    mcp: '/api/mcp',
  },
  notifications: {
    subscribe: '/subscribe',
    unsubscribe: '/unsubscribe',
  },
  channels: {
    root: '/',
    inbox: '/inbox',
    stream: '/stream',
    streamSummary: '/stream/summary',
    rebuild: '/stream/rebuild',
    correct: '/stream/:streamItemId/correct',
    markRead: '/:channelId/read',
    attachItem: '/:channelId/items',
    delete: '/:channelId',
    analytics: '/analytics',
  },
  broadcast: {
    parse: '/parse',
    campaigns: '/campaigns',
    campaignById: '/campaigns/:id',
    campaignPopulate: '/campaigns/:id/populate',
    campaignStart: '/campaigns/:id/start',
    campaignCancel: '/campaigns/:id/cancel',
    campaignRecipients: '/campaigns/:id/recipients',
    campaignStats: '/campaigns/:id/stats',
  },
  auth: {
    requestLoginLink: '/request-login-link',
    loginStatus: '/login-status',
    me: '/me',
    refresh: '/refresh',
    referralPreview: '/referral/:code',
  },
    whatsapp: {
        connect: '/connect',
        qr: '/qr',
        qrForceRefresh: '/qr/force-refresh',
        historyImport: '/history/import',
        historyImports: '/history/imports',
        historyCheckDuplicates: '/history/check-duplicates',
        historyBackfillStream: '/history/backfill-stream',
        status: '/status',
        monitor: '/monitor',
        monitorMessages: '/monitor/messages',
        health: '/health',
        healthDetailed: '/health/detailed',
        historyDebug: '/history/debug',
        healthLogs: '/health/logs',
        events: '/events',
        supportLogs: '/support-logs',
        profile: '/profile',
        messages: '/messages',
        send: '/send',
        sendBulk: '/send-bulk',
        broadcast: '/broadcast',
        disconnect: '/disconnect',
        reset: '/reset',
        resetAll: '/reset-all',
        recipients: '/recipients',
        config: '/config',
    },
  ai: {
    chat: '/chat',
    status: '/status',
    models: '/models',
    usage: '/usage',
    usageReset: '/usage/reset',
    keys: '/keys',
    keysTest: '/keys/test',
    propertySearch: '/property-search',
    history: '/history',
    sessions: '/sessions',
    sessionById: '/sessions/:id',
    sessionClear: '/sessions/:id/clear',
  },
  agent: {
    control: '/control',
    webFetch: '/tool/web_fetch',
    storeLeads: '/tool/store_leads',
  },
  admin: {
    workspaces: '/workspaces',
    updateSubscription: '/workspaces/:tenantId/subscription',
    workspaceGroups: '/workspaces/:tenantId/groups',
    updateWorkspaceGroup: '/workspaces/:tenantId/groups/:groupJid',
    backfillListings: '/backfill/listings',
    backfillPublicListings: '/backfill/public-listings',
    scoutTasks: '/scout/tasks',
    scoutTask: '/scout/tasks/:taskId',
  },
  workspace: {
    overview: '/overview',
    team: '/team',
    updateMember: '/team/:memberId',
    activity: '/activity',
    metadata: '/metadata',
    referral: '/referral',
  },
  voice: {
    speak: '/speak',
    listen: '/listen',
  },
  internal: {
    whatsappInbound: '/whatsapp/inbound',
    whatsappStatus: '/whatsapp/status',
    runtimeSendMessage: '/runtime/send-message',
    runtimeSendMedia: '/runtime/send-media',
    runtimeBroadcast: '/runtime/broadcast',
    runtimeSessionStatus: '/runtime/session/status',
  },
} as const;
