export const ENDPOINTS = {
  auth: {
    requestVerification: '/auth/request-verification',
    verify: '/auth/verify',
    password: '/auth/password',
    me: '/auth/me',
    resetPassword: '/auth/reset-password',
    referralPreview: (code: string) => `/auth/referral/${encodeURIComponent(code)}`,
  },
  ai: {
    chat: '/ai/chat',
    models: '/ai/models',
    status: '/ai/status',
    history: '/ai/history',
  },
  settings: {
    get: '/settings',
    save: '/settings',
  },
  files: {
    upload: '/files/upload',
    list: '/files',
    text: (fileId: string) => `/files/${encodeURIComponent(fileId)}/text`,
  },
  admin: {
    workspaces: '/admin/workspaces',
    updateSubscription: (tenantId: string) => `/admin/workspaces/${tenantId}/subscription`,
    workspaceGroups: (tenantId: string) => `/admin/workspaces/${tenantId}/groups`,
    updateWorkspaceGroup: (tenantId: string, groupJid: string) => `/admin/workspaces/${tenantId}/groups/${encodeURIComponent(groupJid)}`,
    impersonate: (tenantId: string) => `/admin/workspaces/${tenantId}/impersonate`,
    resolveImpersonation: (token: string) => `/admin/impersonation/resolve?token=${encodeURIComponent(token)}`,
    revokeImpersonation: (token: string) => `/admin/impersonation/${encodeURIComponent(token)}`,
    impersonations: '/admin/impersonations',
    audit: '/admin/audit',
  },
  workspace: {
    overview: '/workspace/overview',
    team: '/workspace/team',
    updateMember: (memberId: string) => `/workspace/team/${memberId}`,
    activity: '/workspace/activity',
    metadata: '/workspace/metadata',
    referral: '/workspace/referral',
  },
  whatsapp: {
    connect: '/whatsapp/connect',
    disconnect: '/whatsapp/disconnect',
    status: '/whatsapp/status',
    sessions: '/whatsapp/sessions',
    qr: '/whatsapp/qr',
    monitor: '/whatsapp/monitor',
    inbox: '/whatsapp/inbox',
    health: '/whatsapp/health',
    healthLogs: '/whatsapp/health/logs',
    groupsHealth: '/whatsapp/groups/health',
    events: '/whatsapp/events',
    supportLogs: '/whatsapp/support-logs',
    profile: '/whatsapp/profile',
    config: '/whatsapp/config',
    qrForceRefresh: '/whatsapp/qr/force-refresh',
    historyImport: '/whatsapp/history/import',
    historyImports: '/whatsapp/history/imports',
    historyCheckDuplicates: '/whatsapp/history/check-duplicates',
    groups: '/whatsapp/groups',
    toggleGroupParsing: (groupJid: string) => `/whatsapp/groups/${encodeURIComponent(groupJid)}/toggle-parsing`,
    recipients: '/whatsapp/recipients',
    broadcast: '/whatsapp/broadcast',
    messages: '/whatsapp/messages',
    send: '/whatsapp/send',
    sendBulk: '/whatsapp/send-bulk',
  },
  channels: {
    list: '/channels',
    create: '/channels',
    stream: '/channels/stream',
    analytics: '/channels/analytics',
    rebuild: '/channels/stream/rebuild',
    correct: (streamItemId: string) => `/channels/stream/${streamItemId}/correct`,
    markRead: (channelId: string) => `/channels/${channelId}/read`,
    attachItem: (channelId: string) => `/channels/${channelId}/items`,
  },
  streamItems: {
    list: '/stream-items',
    read: (streamItemId: string) => `/stream-items/${streamItemId}/read`,
    correct: (streamItemId: string) => `/stream-items/${streamItemId}/correct`,
    stats: '/stream-items/stats',
  },
  properties: {
    search: (query: string) => `/properties/search?q=${encodeURIComponent(query)}`,
  },
  identity: {
    onboarding: '/identity/onboarding',
  },
} as const;
