export const ENDPOINTS = {
  auth: {
    requestLoginLink: '/auth/request-login-link',
    loginStatus: '/auth/login-status',
    me: '/auth/me',
    referralPreview: (code: string) => `/auth/referral/${encodeURIComponent(code)}`,
  },
  ai: {
    chat: '/ai/chat',
    models: '/ai/models',
    status: '/ai/status',
    usage: '/ai/usage',
    usageReset: '/ai/usage/reset',
    history: '/ai/history',
    sessions: '/ai/sessions',
    sessionById: (id: string) => `/ai/sessions/${encodeURIComponent(id)}`,
    sessionClear: (id: string) => `/ai/sessions/${encodeURIComponent(id)}/clear`,
    keys: '/ai/keys',
    keysTest: '/ai/keys/test',
  },
  agent: {
    control: '/agent/control',
  },
  settings: {
    get: '/settings',
    save: '/settings',
  },
  files: {
    upload: '/files/upload',
    list: '/files',
    text: (fileId: string) => `/files/${encodeURIComponent(fileId)}/text`,
  },
  admin: {
    workspaces: '/admin/workspaces',
    updateSubscription: (tenantId: string) => `/admin/workspaces/${tenantId}/subscription`,
    workspaceGroups: (tenantId: string) => `/admin/workspaces/${tenantId}/groups`,
    updateWorkspaceGroup: (tenantId: string, groupJid: string) => `/admin/workspaces/${tenantId}/groups/${encodeURIComponent(groupJid)}`,
    impersonate: (tenantId: string) => `/admin/workspaces/${tenantId}/impersonate`,
    resolveImpersonation: (token: string) => `/admin/impersonation/resolve?token=${encodeURIComponent(token)}`,
    revokeImpersonation: (token: string) => `/admin/impersonation/${encodeURIComponent(token)}`,
    impersonations: '/admin/impersonations',
    audit: '/admin/audit',
    parserEvidence: '/admin/parser-evidence',
    scoutTasks: '/admin/scout/tasks',
    scoutTask: (taskId: string) => `/admin/scout/tasks/${encodeURIComponent(taskId)}`,
  },
  workspace: {
    overview: '/workspace/overview',
    team: '/workspace/team',
    updateMember: (memberId: string) => `/workspace/team/${memberId}`,
    activity: '/workspace/activity',
    metadata: '/workspace/metadata',
    referral: '/workspace/referral',
  },
    whatsapp: {
    connect: '/whatsapp/connect',
    disconnect: '/whatsapp/disconnect',
    qr: '/whatsapp/qr',
    status: '/whatsapp/status',
    health: '/whatsapp/health',
    healthDetailed: '/whatsapp/health/detailed',
    healthLogs: '/whatsapp/health/logs',
    events: '/whatsapp/events',
    messages: '/whatsapp/messages',
    inboxThreads: '/whatsapp/inbox/threads',
    inboxMessages: '/whatsapp/inbox/messages',
    send: '/whatsapp/send',
    resetAll: '/whatsapp/reset-all',
    cloudConfig: '/whatsapp/cloud/config',
    cloudWebhook: '/whatsapp/cloud/webhook',
    groups: '/whatsapp/groups',
    groupToggleMonitor: (jid: string) => `/whatsapp/groups/${encodeURIComponent(jid)}/monitor`,
  },
    channels: {
    list: '/channels',
    create: '/channels',
    inbox: '/channels/inbox',
    stream: '/channels/stream',
    streamSummary: '/channels/stream/summary',
    analytics: '/channels/analytics',
    rebuild: '/channels/stream/rebuild',
    correct: (streamItemId: string) => `/channels/stream/${streamItemId}/correct`,
    markRead: (channelId: string) => `/channels/${channelId}/read`,
    attachItem: (channelId: string) => `/channels/${channelId}/items`,
    delete: (channelId: string) => `/channels/${channelId}`,
    search: '/stream-items/search',
  },
  streamItems: {
    list: '/stream-items',
    read: (streamItemId: string) => `/stream-items/${streamItemId}/read`,
    correct: (streamItemId: string) => `/stream-items/${streamItemId}/correct`,
    stats: '/stream-items/stats',
    photos: (streamItemId: string) => `/stream-items/${streamItemId}/photos`,
  },
  waClick: {
    log: '/wa-click',
    stats: '/wa-click/stats',
    listing: (id: string) => `/wa-click/listing/${encodeURIComponent(id)}`,
    export: '/wa-click/export',
  },
  properties: {
    search: (query: string) => `/properties/search?q=${encodeURIComponent(query)}`,
  },
  identity: {
    onboarding: '/identity/onboarding',
  },
  dmContacts: {
    list: '/api/intelligence/dm-contacts',
    tag: '/api/intelligence/dm-contacts/tag',
  },
  brokerContacts: {
    list: '/broker-contacts',
    overlaps: '/broker-contacts/overlaps',
    lists: '/broker-contacts/lists',
    generateLists: '/broker-contacts/lists/generate',
  },
  broadcast: {
    campaigns: '/broadcast/campaigns',
    campaignById: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}`,
    campaignPopulate: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/populate`,
    campaignStart: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/start`,
    campaignCancel: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/cancel`,
    campaignRecipients: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/recipients`,
    campaignStats: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/stats`,
  },
  syndication: {
    list: '/syndication/partners',
    invite: '/syndication/invite',
    accept: '/syndication/accept',
    partners: '/syndication/partners',
    revoke: (id: string) => `/syndication/${encodeURIComponent(id)}`,
  },
  mcp: {
    token: '/mcp/token',
  },
} as const;
