export const ENDPOINTS = {
  auth: {
    requestVerification: '/auth/request-verification',
    verify: '/auth/verify',
    password: '/auth/password',
    me: '/auth/me',
    resetPassword: '/auth/reset-password',
    referralPreview: (code: string) => `/auth/referral/${encodeURIComponent(code)}`,
  },
  ai: {
    chat: '/ai/chat',
    models: '/ai/models',
    status: '/ai/status',
    usage: '/ai/usage',
    usageReset: '/ai/usage/reset',
    history: '/ai/history',
    sessions: '/ai/sessions',
    sessionById: (id: string) => `/ai/sessions/${encodeURIComponent(id)}`,
    sessionClear: (id: string) => `/ai/sessions/${encodeURIComponent(id)}/clear`,
  },
  agent: {
    control: '/agent/control',
  },
  settings: {
    get: '/settings',
    save: '/settings',
  },
  files: {
    upload: '/files/upload',
    list: '/files',
    text: (fileId: string) => `/files/${encodeURIComponent(fileId)}/text`,
  },
  admin: {
    workspaces: '/admin/workspaces',
    updateSubscription: (tenantId: string) => `/admin/workspaces/${tenantId}/subscription`,
    workspaceGroups: (tenantId: string) => `/admin/workspaces/${tenantId}/groups`,
    updateWorkspaceGroup: (tenantId: string, groupJid: string) => `/admin/workspaces/${tenantId}/groups/${encodeURIComponent(groupJid)}`,
    impersonate: (tenantId: string) => `/admin/workspaces/${tenantId}/impersonate`,
    resolveImpersonation: (token: string) => `/admin/impersonation/resolve?token=${encodeURIComponent(token)}`,
    revokeImpersonation: (token: string) => `/admin/impersonation/${encodeURIComponent(token)}`,
    impersonations: '/admin/impersonations',
    audit: '/admin/audit',
    scoutTasks: '/admin/scout/tasks',
    scoutTask: (taskId: string) => `/admin/scout/tasks/${encodeURIComponent(taskId)}`,
  },
  workspace: {
    overview: '/workspace/overview',
    team: '/workspace/team',
    updateMember: (memberId: string) => `/workspace/team/${memberId}`,
    activity: '/workspace/activity',
    metadata: '/workspace/metadata',
    referral: '/workspace/referral',
  },
    whatsapp: {
    connect: '/whatsapp/connect',
    disconnect: '/whatsapp/disconnect',
    reset: '/whatsapp/reset',
    resetAll: '/whatsapp/reset-all',
    status: '/whatsapp/status',
    sessions: '/whatsapp/sessions',
    qr: '/whatsapp/qr',
    monitorMessages: '/whatsapp/monitor/messages',
    health: '/whatsapp/health',
    healthLogs: '/whatsapp/health/logs',
    groupsHealth: '/whatsapp/groups/health',
    events: '/whatsapp/events',
    supportLogs: '/whatsapp/support-logs',
    profile: '/whatsapp/profile',
    config: '/whatsapp/config',
    reconnect: '/whatsapp/qr/force-refresh',
    qrForceRefresh: '/whatsapp/qr/force-refresh',
    historyImport: '/whatsapp/history/import',
    historyImports: '/whatsapp/history/imports',
    historyCheckDuplicates: '/whatsapp/history/check-duplicates',
    groups: '/whatsapp/groups',
    groupsAudit: '/whatsapp/groups/audit',
    auditAllowAll: '/whatsapp/groups/audit/allow-real-estate',
    rescanGroups: '/whatsapp/groups/rescan',
    groupStreamItems: (groupJid: string) => `/whatsapp/groups/${encodeURIComponent(groupJid)}/stream-items`,
    toggleGroupParsing: (groupJid: string) => `/whatsapp/groups/${encodeURIComponent(groupJid)}/toggle-parsing`,
    updateGroupVisibility: (groupJid: string) => `/whatsapp/groups/${encodeURIComponent(groupJid)}/visibility`,
    recipients: '/whatsapp/recipients',
    broadcast: '/whatsapp/broadcast',
    messages: '/whatsapp/messages',
    send: '/whatsapp/send',
    sendBulk: '/whatsapp/send-bulk',
    cloudConfig: '/whatsapp/cloud/config',
    cloudWebhook: '/whatsapp/cloud/webhook',
  },
  channels: {
    list: '/channels',
    create: '/channels',
    inbox: '/channels/inbox',
    stream: '/channels/stream',
    streamSummary: '/channels/stream/summary',
    analytics: '/channels/analytics',
    rebuild: '/channels/stream/rebuild',
    correct: (streamItemId: string) => `/channels/stream/${streamItemId}/correct`,
    markRead: (channelId: string) => `/channels/${channelId}/read`,
    attachItem: (channelId: string) => `/channels/${channelId}/items`,
    search: '/stream-items/search',
  },
  streamItems: {
    list: '/stream-items',
    read: (streamItemId: string) => `/stream-items/${streamItemId}/read`,
    correct: (streamItemId: string) => `/stream-items/${streamItemId}/correct`,
    stats: '/stream-items/stats',
  },
  waClick: {
    log: '/wa-click',
    stats: '/wa-click/stats',
    listing: (id: string) => `/wa-click/listing/${encodeURIComponent(id)}`,
    export: '/wa-click/export',
  },
  igr: {
    search: '/igr/search',
    fetch: '/igr/fetch',
    buildingNames: '/igr/building-names',
  },
  properties: {
    search: (query: string) => `/properties/search?q=${encodeURIComponent(query)}`,
  },
  identity: {
    onboarding: '/identity/onboarding',
  },
  dmContacts: {
    list: '/api/intelligence/dm-contacts',
    tag: '/api/intelligence/dm-contacts/tag',
  },
  brokerContacts: {
    list: '/broker-contacts',
    overlaps: '/broker-contacts/overlaps',
    lists: '/broker-contacts/lists',
    generateLists: '/broker-contacts/lists/generate',
  },
  broadcast: {
    campaigns: '/broadcast/campaigns',
    campaignById: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}`,
    campaignPopulate: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/populate`,
    campaignStart: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/start`,
    campaignCancel: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/cancel`,
    campaignRecipients: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/recipients`,
    campaignStats: (id: string) => `/broadcast/campaigns/${encodeURIComponent(id)}/stats`,
  },
  syndication: {
    invite: '/syndication/invite',
    accept: '/syndication/accept',
    feed: '/syndication/feed',
    list: '/syndication/list',
    revoke: (id: string) => `/syndication/${encodeURIComponent(id)}`,
  },
} as const;
